freetype/__init__.py
freetype/raw.py

This should make things a bit better for people who want to use the ctypes binding directly, instead of the pythonic wrapper.
This still may need some work, and i haven't tested it thoroughly.

Split the ctypes function binding out into raw.py.

---

freetype/__init__.py

In python 2 the injected \_\_del\_\_ method was called, but by the time FT_Library was deleted the FT\_Done\_FreeType function was gone. This has been worked around by storing a reference of FT\_Done\_FreeType.
However under python 3  there was a second issue. For whatever reason the injected \_\_del\_\_ method wasn't called at all. They work on a normal classes and subclasses in python 3, so I'm not completely sure what was going on there. Fixed this by just subclassing FT_Library, and defining the needed stuff in there.
This also has a nice side effect of no longer injecting the \_\_del\_\_ function into the raw FT_Library, which also effected anyone using freetype raw.

Fix FT_Done_FreeType never being called on FT_Library instance.

---

examples/emoji-color.py
freetype/ft_enums/ft_load_flags.py

FT_LOAD_COLOR was added to the ft_load_flags.py. When this flag is
given, freetype will return a bgra version of emoji chars instead of
grey scale.
Tested with "Apple Color Emoji.ttc".

Added FT_LOAD_COLOR to load color version emoji

---

examples/agg-trick.py
examples/emoji-color.py
examples/glyph-color.py
examples/glyph-outline.py
examples/texture_font.py
freetype/__init__.py
freetype/raw.py

This is taken from fedora's build farm, so it is possible that other freetype builds have fewer symbols... However, 2.2.X is more than a decade old!

Adding symbols from 2.2.X onwards

---

examples/bitmap_to_surface.py
examples/emoji-color-cairo.py
examples/example_1-cairo.py
examples/glyph-color-cairo.py
examples/glyph-lcd-cairo.py
examples/glyph-lcd.py
examples/glyph-mono+alpha-cairo.py
examples/glyph-outline-cairo.py
examples/glyph-vector-2-cairo.py
examples/glyph-vector-2.py
examples/glyph-vector-cairo.py
examples/glyph-vector.py
examples/hello-world-cairo.py
examples/wordle-cairo.py
freetype/__init__.py
freetype/ft_enums/__init__.py
freetype/ft_enums/ft_curve_tags.py
freetype/ft_types.py

Should work also with cairocffi.
TODO/Limitations:
- glyph-mono+alpha requires libtiff on small-endian platforms
for mono-rendering to bitswap correctly. It may be possible to use
FT_Bitmap_Convert() instead. TODO
**edit** I wanted to do strikethrough to keep the paragraph but indicates that the below nolonger applies.
Already fixed by further commits later.
```
- wordle requires pycairo 1.11+ (released only on 2017-04-09)
for the overlap check, and does not pack as tightly. Further work.
Changing paint color/alpha also not seem to work. Investigate.
```

pycairo based rewrite of the drawing examples.

---

freetype/__init__.py

FT2 demo's ftdump ignores the return code of FT_Set_Charmap.
FT_Set_Charmap is known to fail when type~14 charmap is selected
(which doesn't map character codes to glyph indices at all).
This is a harmless situation. OpenType 1.8 fonts with Variations shows:
"format 14, platform 0, encoding  5   (Unicode Variation Sequences)"
An example is the Google Noto CJK /Adobe Source Sans fonts.
Also minor addition to API: auto-detect input type, and allow input as
integer index also.

Allow Type 14 charmap to fail in FT_Set_Charmap.

---

setup.py

When I tried to install 1.1 release I found its generating old 1.0.2 versioned egg-info directory. 
This pull-request will try to fix version in setup.py.
I have advanced the version to 1.2 so that you can release it directly after committing this patch.
Feel free to modify the patch if you want different version number.
Signed-off-by: Parag Nemade <pnemade@fedoraproject.org>

Update the version in setup.py

---

freetype/raw.py

See
https://github.com/rougier/freetype-py/issues/65

Protect symbols not in default visual studio build of freetype 2.8.x

---

README.rst
setup.py

Extended the Windows-section of the readme file. Some of the information is also availible on the issue page.

Add information to readme for FreeType installation on windows

---

freetype/__init__.py

I haven't looked at the source closely, but more functions may need a vetting.

Avoid segfault on passing non-binary data to FT_Get_Name_Index

---

setup.py

Force the encoding = "utf-8" instead of the default Windows codec

Fix #72: install on Python 3.6 on Windows

---

README.rst

Fixes #75 
I checked by installing `readme_renderer` and running `python setup.py check --restructuredtext --strict`

README.rst: fix invalid markup that fails to render on PyPI

---

tests/test_ft_face.py
tox.ini

First stop: add basic smoke test for py27, py36. The test only sees if stuff loads after a tox-controlled install.
Next: Setting up some CI service to tox on Windows, macOS and some Linux. That's probably the hard part.

Setup CI testing

---

.travis.yml
appveyor.yml
ci/custom_docker.sh
ci/multibuild_config.sh
setup-build-freetype.py
setup.cfg

Edit: So, the 2.0 release was botched. The bundling didn't work on Linux because the FREETYPEPY_BUNDLE_FT variable didn't reach the Docker container. This PR makes it work. AppVeyor deployment may need a separate fix.

Unbreak CI wheel building on Linux

---

setup.py

Instead of specifying it manually. Makes it possible to release a version by tagging it in GitHub.

Use setuptools_scm to set package version

---

.travis.yml
appveyor.yml

cmd.exe doesn't expand *.whl and newer twine versions work better with PowerShell, so get rid of the hack.
Also generate sdist on deploy.

Fix AppVeyor deployment script and add sdist

---

freetype/__init__.py
tests/smoke_test.py

The fourth PR to tackle loading a font from memory instead of from disk. 
- Since we still have to support Python 2(?), testing the `file_or_stream` argument for being a `bytes` object won't work, accept a `io.BytesIO` object instead.
- Implement @rougier's suggestion at https://github.com/rougier/freetype-py/pull/33#issuecomment-167834852. Since loading from a path is the default, I did not add a `from_file` class method. It would make more sense when `Face::__init__` is refactored to not have any logic and just stores what it's given.
Not sure what to do about `Face::_filename`. it doesn't seem to be used anywhere.
Working on `attach_file`, I need a test case.
Closes https://github.com/rougier/freetype-py/pull/33, https://github.com/rougier/freetype-py/pull/103, …

Implement Face loading from memory

---

.travis.yml
appveyor.yml

The packages for 3.6 are universal because we don't depend on CPython internals. Duh.

Remove Python 3.7 from CI build

---

examples/glyph-vector-decompose.py
freetype/__init__.py
freetype/ft_structs.py

I wanted access to FT_Outline_Decompose(), so I added it in. See  examples/glyph-vector-decompose.py for example use.
I tried to follow existing conventions, I can fix things up if I made a blunder. Thanks for considering this PR!

Expose FT_Outline_Decompose() as Outline.decompose(), with example

---

freetype/__init__.py

see issue: https://github.com/rougier/freetype-py/issues/35
FT_Glyph_Get_CBox function in c (freetype: src/base/ftglyph.c):
```
FT_Glyph_Get_CBox( FT_Glyph  glyph,
FT_UInt   bbox_mode,
FT_BBox  *acbox )
{
// ...
}
```
receive glyph with FT_Glyph type, but you send byref(self._FT_Glyph) with *FT_Glyph type.

Fix bug: Glyph bounding box does not work

---

.github/workflows/ci.yml
setup.py

follows recommendation in https://github.com/pypa/setuptools_scm#pyprojecttoml-usage
Fixes https://github.com/rougier/freetype-py/issues/128

setup.py: no need to specifiy toml extra in setup_requires

---

setup-build-freetype.py

Hello,
during the build process on a Raspberry Pi I got an error from cmake, that the `-m32` or `-m64` flag is not supported on this platform.
So I reworked the code to detect not only if the system is 32/64bit but also if it's an ARM system. There's also support for `aarch64`.

support for ARM builds

---

freetype/__init__.py
freetype/ft_enums/ft_render_modes.py
freetype/raw.py
setup-build-freetype.py

- Ups the freetype version to 2.11
- Adds the `FT_RENDER_MODE_SDF` flag
- Adds the `render` method to `GlyphSlot` corresponding to `FT_Render_Glyph`
There is no `FT_LOAD_TARGET_XXX` for SDF, so an api for `FT_Render_Glyph` is required to render an SDF. Not sure if this is an oversight in the freetype API or by design.

Add support for SDF rendering.

---

.github/workflows/ci.yml

Closes #138
* This upgrades CI to use the latest version of cibuildwheel and adds apple silicon wheels to the build configuration.
* Apple silicon wheels can only be built for python >=3.8.
* This newer version of cibuildwheel also happens to build musllinux wheels, so that's a free bonus, I guess!
* Split out the publish to pypi job

Add arm64 to build matrix and update cibuildwheel

---

freetype/raw.py

I noticed that [`FT_Outline_EmboldenXY()`](https://freetype.org/freetype2/docs/reference/ft2-outline_processing.html#ft_outline_emboldenxy) looks missing in `raw.py`, which is an enhanced variant to `FT_Outline_Embolden()`.
Adding a Pythonic binding should be trivial, but I'm not sure it's worth it.

Expose binding to FT_Outline_EmboldenXY()

---

.github/workflows/ci.yml

This adds aarch64 builds for manylinux and musllinux using QEMU. That makes the wheel installable on e.g. raspberry pi.
I added them as separate jobs to the build matrix as they are quite slow.

Add aarch64 builds to CI build matrix

---

examples/outline-test.py
freetype/__init__.py

- Cannot call `FT_Outline_GetOutsideBorder()` due to typo, which is needed to use `FT_Stroker`
- Some methods pass `FT_Outline` without wrapping with `ctypes.byref()`
- `Stroker.parse_outline()` currently accepts `byref(FT_Outline)` instead of `Outline`
Some of the existing Python bindings for `FT_Outline` didn't work for me. This PR is intended to address those.

Fix bindings for FT_Outline

---

.github/workflows/ci.yml
README.rst
freetype/__pyinstaller/__init__.py
freetype/__pyinstaller/conftest.py
freetype/__pyinstaller/hook-freetype.py
freetype/__pyinstaller/test_freetype.py
setup.py

This adds a pyinstaller hook to freetype which is made discoverable using an entry point. That means that if projects wish to freeze their python application using pyinstaller, pyinstaller will automatically know that it should include the freetype binary in the package.
It includes a pytest setup that is also run on CI, which ensures that freetype can be imported from a pyinstaller-frozen application. This makes sure the hook won't be broken in the future.
(Reason for this change is that we are ensuring wgpu-py and pygfx are pyinstaller compatible by default, and freetype became one of our dependencies, so I'm contributing pyinstaller support coming from that angle :)

Add pyinstaller hook

---

freetype/__init__.py

When we're called during the interpreter shutdown, the functions we need may already be set to None.  So check for that before trying to call them which fixes the "'NoneType' object is not callable" errors described in issues #44 and #169.

freetype.Face.__del__: check first if FT_Face_Done has been set to None (#169)

---

.github/workflows/ci.yml
_custom_build/backend.py
pyproject.toml

Fixes https://github.com/rougier/freetype-py/issues/183
`pip install --no-binary freetype-py freetype-py` will no longer attempt to download and install cmake in pip's temporary build environment, unless FREETYPEPY_BUNDLE_FT environment variable was set in order to compile the bundled FreeType shared library.
This makes the installation of a pure Python freetype-py (using system-wide FreeType library) quicker and doesn't require one to force --no-build-isolation just to prevent cmake from being installed unnecessarily.

use custom PEP517 build backend to require cmake conditionally

---

freetype/__init__.py
tests/smoke_test.py

The symbol `FT_FSTYPE_XXX` does not exist in `freetype/ft_enums/ft_fstypes.py`, and instead it is named `FT_FSTYPES` in that file.
`Face.get_fstype()` used the (maybe) wrong name and raises an error when calling it.

Fix wrong enum name in Face.get_fstype()

---

doc/ft_encodings.rst
doc/tt_ms_ids.rst
examples/font-info.py
examples/ftdump.py
freetype/ft_enums/ft_encodings.py
freetype/ft_enums/tt_ms_ids.py

And misc corrections of examples.

Ft encoding fix

---

examples/hello-world.py

If the string contains a ',' the example code produces the following error:
```
Traceback (most recent call last):
File "hello-world.py", line 47, in <module>
Z[y:y+h,x:x+w] += numpy.array(bitmap.buffer, dtype='ubyte').reshape(h,w)
ValueError: operands could not be broadcast together with shapes (0,28) (35,28) (0,28)
```
If the string in the hello-world example contains some characters which passes the baseline the bbox calculation fails. This will be the case when a ',' is added to the example string.

Fix bbox calculation in hello-world example
